title: Ákos Hajdu
logo: /assets/img/hajduakos.jpg
description: Computer scientist, PhD
website1: https://about.facebook.com/meta/
affiliation1: Meta
title1: Software Engineer
scholar: 7z74iO8AAAAJ
mail: akoshajdu@meta.com
linkedin: akoshajdu
dblp: https://dblp.uni-trier.de/pers/hd/h/Hajdu:=Aacute=kos
twitter: himynameisakos
flickr: sonic182
theme: jekyll-theme-minimal
