title: Ákos Hajdu
logo: /assets/img/hajduakos.jpg
description: Computer scientist
title1: Assistant lecturer
affiliation1: BME MIT FTSRG
website1: http://inf.mit.bme.hu/en
scholar: 7z74iO8AAAAJ
mail: hajdua@mit.bme.hu
linkedin: akoshajdu
dblp: https://dblp.uni-trier.de/pers/hd/h/Hajdu:=Aacute=kos
cv: https://hajduakos.github.io/hajdua-cv/hajdua_cv_en.pdf
cvlong: https://hajduakos.github.io/hajdua-cv/hajdua_cv_en_long.pdf
twitter: himynameisakos
instagram: photosbyakos
flickr: sonic182
theme: jekyll-theme-minimal
