title: Akos Hajdu
logo: /assets/img/hajduakos.jpg
description: Computer scientist
title1: PhD Candidate
affiliation1: BME MIT FTSRG
website1: http://inf.mit.bme.hu/en
title2: Research intern
affiliation2: SRI International
website2: https://www.sri.com/
scholar: https://scholar.google.hu/citations?user=7z74iO8AAAAJ
mail: hajdua@mit.bme.hu
linkedin: https://www.linkedin.com/in/akoshajdu/
dblp: https://dblp.uni-trier.de/pers/hd/h/Hajdu:=Aacute=kos
theme: jekyll-theme-minimal