title: Akos Hajdu
logo: /assets/img/hajduakos.jpg
description: Computer scientist
title1: PhD Candidate
affiliation1: BME MIT FTSRG
website1: http://inf.mit.bme.hu/en
title2: Research intern
affiliation2: SRI International
website2: https://www.sri.com/
theme: jekyll-theme-minimal