title: Ákos Hajdu
logo: /assets/img/hajduakos.jpg
description: Computer scientist
title1: PhD Candidate
affiliation1: BME MIT FTSRG
website1: http://inf.mit.bme.hu/en
scholar: https://scholar.google.hu/citations?user=7z74iO8AAAAJ
mail: hajdua@mit.bme.hu
linkedin: https://www.linkedin.com/in/akoshajdu/
dblp: https://dblp.uni-trier.de/pers/hd/h/Hajdu:=Aacute=kos
cv: https://hajduakos.github.io/hajdua-cv/hajdua_cv_en.pdf
cvlong: https://hajduakos.github.io/hajdua-cv/hajdua_cv_en_long.pdf
theme: jekyll-theme-minimal
